name: flask-app-cicd

on:
  push:
    branches:
      - main

permissions:
  contents: write

env:
  IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/flask-app
  IMAGE_TAG: v3
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image And Push
        run: |

          docker build -t $IMAGE_NAME:$IMAGE_TAG ./flask-app
          docker push $IMAGE_NAME:$IMAGE_TAG

      - name: Update manifest with new image tag
        run: |
          sed -i "s|image: .*|image: $IMAGE_NAME:$IMAGE_TAG|" flask-app/k8s/deployment.yaml

      - name: Commit and push changes
        env:
          MY_GITHUB_PAT: ${{ secrets.MY_GITHUB_PAT }}
        run: |
          cd flask-app
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add flask-app/k8s/deployment.yaml
          git commit -m "Update deployment.yaml to $IMAGE_NAME:$IMAGE_TAG"
          git push https://x-access-token:${MY_GITHUB_PAT}@github.com/${{ github.repository }} HEAD:main